version: '3'

networks:
  laravel:

services:
  site:
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: ${COMPOSER_APP_NAME}_nginx
    ports:
      - "8088:80"
    volumes:
      # 如果多幾層路徑的話就會碰到這個問題，疑似是權限問題
      # https://segmentfault.com/a/1190000017789890
      - ./src:/var/www/html:delegated
    depends_on:
      - php
      - postgres
    networks:
      - laravel

  postgres:
    image: postgres:13
    container_name: ${COMPOSER_APP_NAME}_postgres
    # restart: unless-stopped
    tty: true
    ports:
      - "15432:5432"
    environment:
      POSTGRES_DB: homestead
      POSTGRES_USER: homestead
      POSTGRES_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: postgres
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: ${COMPOSER_APP_NAME}_php
    volumes:
      - ./src:/var/www/html:delegated
    ports:
      - "9000:9000"
    networks:
      - laravel

  composer:
    build:
      context: .
      dockerfile: composer.dockerfile
    container_name: composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    user: laravel
    networks:
      - laravel
    entrypoint: ['composer', '--ignore-platform-reqs']

  npm:
    image: node:13.7
    container_name: ${COMPOSER_APP_NAME}_npm
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']

  artisan:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: ${COMPOSER_APP_NAME}_artisan
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - postgres
    working_dir: /var/www/html
    user: laravel
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - laravel
